fixed tar test, and added bz2 test

diff --git a/webdav-test b/webdav-test
--- a/webdav-test
+++ b/webdav-test
@@ -323,13 +323,37 @@ then
 	read -n 1 -s
 fi
 
+# bz2 test 1
+echo Starting bz2 test 1
+
+echo '<!-- bzip2 test -->' > "${TEMP_DOC}"
+echo '<!-- bzip2 test -->' > "${TEST_DOC}"
+
+bzip2 -k "${TEMP_DOC}"
+bzip2 -k "${TEST_DOC}"
+
+bzcmp "${TEMP_DOC}.bz2" "${TEST_DOC}.bz2"
+
+if [[ $? -ne 0 ]]
+then
+echo "************ bz2 test 2 failed ************"
+read -n 1 -s
+fi
+
 # tar test 1
 echo Starting tar test 1
-echo '<!-- sed test -->' > "${TEMP_DOC}"
-echo '<!-- sed test -->' > "${TEST_DOC}"
+echo '<!-- tar test -->' > "${TEMP_DOC}"
+echo '<!-- tar test -->' > "${TEST_DOC}"
 tar -C "${TEMP_DIR}" -cjf /tmp/tar1.tar.bz2 "${TEST_FILENAME}"
 tar -C "${TEST_DIR}" -cjf /tmp/tar2.tar.bz2 "${TEST_FILENAME}"
-diff /tmp/tar1.tar.bz2 /tmp/tar2.tar.bz2
+
+mkdir /tmp/temp
+mkdir /tmp/temp2
+
+cd /tmp/temp; tar -xjf /tmp/tar1.tar.bz2
+cd /tmp/temp2; tar -xjf /tmp/tar2.tar.bz2
+
+diff "/tmp/temp/${TEST_FILENAME}" "/tmp/temp2/${TEST_FILENAME}"
 
 if [[ $? -ne 0 ]]
 then
