Fixed tests to take upload delay into account.

diff --git a/webdav-test b/webdav-test
--- a/webdav-test
+++ b/webdav-test
@@ -6,7 +6,7 @@
 # The default delay between a file being saved, and it being uploaded by davfs (plus a small margin)
 UPLOAD_DELAY=12
 
-DOWNLOAD_DELAY=20
+DOWNLOAD_DELAY=15
 
 MOUNT_DIR="/mnt/pressgang/TOPICS"
 TEST_FILENAME=3737.xml
@@ -29,7 +29,59 @@ XML_FORMAT_LOCATION=/opt/xmlformat-1.04
 cd "${TEST_DIR}"
 find * -maxdepth 0 -name '3737.xml' -prune -o -exec rm -rf '{}' ';'
 
+# touch test 1
 
+# This is a tricky situation, because we are doing something that the file system does
+# not expect. we create, delete and touch a file to simulate the "deletion" and
+# reappearance of a file. The file was never deleted, but the caching done by davfs2
+# makes it seem that way. Hence all the sleeps
+
+echo Starting touch test 1
+echo "    Redirect an echo"
+echo '<!-- rm test 1 -->' > "${TEST_DOC}"
+echo '<!-- rm test 1 -->' > "${TEMP_DOC}"
+
+# wait for echo above to be uploaded to the server
+sleep ${UPLOAD_DELAY}
+
+# delete the file and wait for the delete to be propagated to the server
+echo "    Delete and touch the file"
+rm "${TEST_DOC}"
+
+# create an empty file and wait for the creation to be propagated to the server
+touch "${TEST_DOC}"
+sleep ${UPLOAD_DELAY}
+sleep ${DOWNLOAD_DELAY}
+
+echo "    Diff the file"
+diff "${TEST_DOC}" "${TEMP_DOC}"
+
+if [[ $? -ne 0 ]]
+then
+    echo "************ touch test 1 failed  ************"
+    read -n 1 -s
+fi
+
+# touch test 2
+echo Starting touch test 2
+echo '<section><title>test</title><para>hi</para></section>' > "${TEMP_DOC}"
+echo '<section><title>test</title><para>hi</para></section>' > "${TEST_DOC}"
+
+sleep ${UPLOAD_DELAY}
+
+# touching the file should clear the cache
+> "${TEST_DOC}"
+sleep ${UPLOAD_DELAY}
+sleep ${DOWNLOAD_DELAY}
+
+# the test doc should be formatted, while the temp doc will not be
+diff "${TEST_DOC}" "${TEMP_DOC}"
+
+if [[ $? -eq 0 ]]
+then
+	echo "************ touch test 2 failed  ************"
+	read -n 1 -s
+fi
 
 # cp test 1
 echo Starting cp test 1
@@ -136,74 +188,7 @@ then
 	read -n 1 -s
 fi
 
-# touch test 1
 
-# This is a tricky situation, because we are doing something that the file system does
-# not expect. we create, delete and touch a file to simulate the "deletion" and
-# reappearance of a file. The file was never deleted, but the caching done by davfs2
-# makes it seem that way. Hence all the sleeps
-
-echo Starting touch test 1
-echo "    Redirect an echo"
-echo '<!-- rm test 1 -->' > "${TEST_DOC}"
-echo '<!-- rm test 1 -->' > "${TEMP_DOC}"
-
-# wait for echo above to be uploaded to the server
-sleep ${UPLOAD_DELAY}
-
-# delete the file and wait for the delete to be propagated to the server
-echo "    Delete and touch the file"
-rm "${TEST_DOC}"
-
-# create an empty file and wait for the creation to be propagated to the server
-touch "${TEST_DOC}"
-sleep ${UPLOAD_DELAY}
-
-# update the directory listing
-#ls -la  "${TEST_DIR}"
-#sleep ${UPLOAD_DELAY}
-
-# This combination of calls refreshes the davfs cache. I don't actually know why this works
-# but you need to open the file twice with at least a 2 second delay in-between before
-# the files contents from the server is available.
-echo "    Cat the file"
-cat "${TEST_DOC}"
-sleep 2
-cat "${TEST_DOC}"
-sleep 2
-
-echo "    Diff the file"
-diff "${TEST_DOC}" "${TEMP_DOC}"
-
-if [[ $? -ne 0 ]]
-then
-    echo "************ touch test 1 failed  ************"
-    read -n 1 -s
-fi
-
-# touch test 2
-echo Starting touch test 2
-echo '<section><title>test</title><para>hi</para></section>' > "${TEMP_DOC}"
-echo '<section><title>test</title><para>hi</para></section>' > "${TEST_DOC}"
-
-sleep ${UPLOAD_DELAY}
-
-# touching the file should clear the cache
-> "${TEST_DOC}"
-sleep ${UPLOAD_DELAY}
-
-echo "    Cat the file"
-cat "${TEST_DOC}"
-sleep 2
-
-# the test doc should be formatted, while the temp doc will not be
-diff "${TEST_DOC}" "${TEMP_DOC}"
-
-if [[ $? -eq 0 ]]
-then
-	echo "************ touch test 2 failed  ************"
-	read -n 1 -s
-fi
 
 # cat test 1
 echo Starting cat test 1
